MarshrutkaBy/Models/Cars.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MarshrutkaBy.Models
{
    [Table("Cars")]
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.DataRoute = new HashSet<DataRoute>();
        }

        [Key]
        public int IdCar { get; set; }

        [Required]
        [Display(Name = "Регистрационный номер")]
        public string NumberPlate { get; set; }

        [Required]
        [Display(Name = "Марка и модель авто")]
        public string ModelCars { get; set; }

        [Display(Name = "Цвет")]
        public string Color { get; set; }

        [Required]
        [Display(Name = "Доп. услуги")]
        public string Services { get; set; }

        [Display(Name = "Количество мест")]
        public int NumberOfSeats { get; set; }

        [Display(Name = "Фото")]
        public string Photo { get; set; }

        [Required]
        public string IdTransportCompanies { get; set; }

        public virtual TransportCompanies TransportCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataRoute> DataRoute { get; set; }
    }
}

MarshrutkaBy/Models/Drivers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MarshrutkaBy.Models
{
    [Table("Drivers")]
    public partial class Drivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drivers()
        {
            this.DataRoute = new HashSet<DataRoute>();
        }

        [Key]
        public int IdDriver { get; set; }

        [Display(Name = "Фамилия")]
        [Required]
        public string LastName { get; set; }

        [Display(Name = "Имя")]
        [Required]
        public string FirstName { get; set; }

        
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "День рождения")]
        public DateTime Birthday { get; set; }

        [Display(Name = "Лицензия")]
        [Required]
        public string License { get; set; }

        [Display(Name = "Номер телефона")]
        [Required]
        public string NumberPhone { get; set; }

        [Required]
        public string Email { get; set; }

        [Display(Name = "Рейтинг")]
        public int Raiting { get; set; }

        [Display(Name = "Фото")]
        public string Photo { get; set; }

        [Required]
        public string UserId { get; set; }

        [Required]
        public string IdTransportCompanies { get; set; }

        public virtual TransportCompanies TransportCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataRoute> DataRoute { get; set; }
    }
}

MarshrutkaBy/Controllers/CompanyController.cs
using MarshrutkaBy.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace MarshrutkaBy.Controllers
{
    public class CompanyController : Controller
    {
        private const string Verification = "Подтверждение бронирования";
        private const string NonVerification = "Анулирование бронирования";
        Models.ApplicationDbContext db = new Models.ApplicationDbContext();
        public static string idCurrentUser;
        private ApplicationUserManager _userManager;
        private static int idDataroute;
        // GET: Company
        public int GetIdCompany()
        {
            idCurrentUser = User.Identity.GetUserId();
            var admincompany = db.AdminTransportCompanies.Find(idCurrentUser);
            return admincompany.IdTransportCompanies;
        }

        public ActionResult Index()
        {
            if (GetIdCompany() != 0)
            {
                var company = db.TransportCompanies.Find(GetIdCompany());
                return View(company);
            }
            return View();
        }

        

        public ActionResult NonVerificatedOrder()
        {
            var idTC = GetIdCompany();
            //var dataRoutes = db.DataRoute.Where(x => x.IdTransportCompanies == idTC)
            
            var order = db.Order.Where(x => x.DataRoute.IdTransportCompanies == idTC & x.Verification == null);
          

            if (order.Count() != 0)
            {
                return PartialView(order.ToList());
            }
            return PartialView();
        }

        public async Task<ActionResult> Verificated(int id)
        {
            string filePath = AppDomain.CurrentDomain.BaseDirectory + @"\verification.txt";
            var order1 = db.Order.Find(id);
            var email = db.Users.Find(order1.IdUser);
            order1.Verification = "Подтверждено";
            db.SaveChanges();

            await SendEmailAsync(email.Email, Verification, BodyText(filePath, order1.IdOrder, Convert.ToString(order1.OrderTime), order1.DataRoute.Cars.ModelCars + " " + order1.DataRoute.Cars.NumberPlate, order1.DataRoute.Routes.StartingPoint + " - " + order1.DataRoute.Routes.EndPoint, Convert.ToString(order1.DataRoute.Date + " " + order1.DataRoute.Times.DepartureTime), order1.DataRoute.Price));

            return RedirectToAction("Routes");
        }

        public async Task<ActionResult> NonVerificated(int id)
        {
            string filePath = AppDomain.CurrentDomain.BaseDirectory + @"\nonverification.txt";
            var order1 = db.Order.Find(id);
            var email = db.Users.Find(order1.IdUser);
            order1.Verification = "Отменено";
            db.SaveChanges();

            await SendEmailAsync(email.Email, NonVerification, BodyText(filePath, order1.IdOrder, Convert.ToString(order1.OrderTime), order1.DataRoute.Cars.ModelCars + " " + order1.DataRoute.Cars.NumberPlate, order1.DataRoute.Routes.StartingPoint + " - " + order1.DataRoute.Routes.EndPoint, Convert.ToString(order1.DataRoute.Date + " " + order1.DataRoute.Times.DepartureTime), order1.DataRoute.Price));

            return RedirectToAction("Routes");
        }

        public string BodyText(string filePath, int idOrder, string date, string modelAndNumberOfPalte, string routes, string dateRoute, int price)
        {

            StreamReader file = new StreamReader(filePath, Encoding.Default, true);
            var text = String.Format(file.ReadToEnd(), idOrder, date, modelAndNumberOfPalte, routes, dateRoute, price);

            return text;
        }

        private static async Task SendEmailAsync(string email, string subject, string text)
        {
            MailAddress from = new MailAddress("pahazavoronok@gmail.com", "Marshrutka.by");
            MailAddress to = new MailAddress(email);
            MailMessage m = new MailMessage(from, to)
            {
                Subject = subject,
                Body = text
            };
            SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587)
            {
                Credentials = new NetworkCredential("pahazavoronok@gmail.com", "11235813213455Paha"),
                EnableSsl = true
            };
            try
            {
                await smtp.SendMailAsync(m);
            }
            catch (SmtpException ex)
            {
                Console.WriteLine(ex.Message.ToString());
            }

        }

        public ActionResult Details(int id)
        {
            var order = db.Order.Where(x => x.IdDataRoute == id && x.Verification == "Подтверждено").ToList();

            if (order.Count() != 0)
            {
                return View(order);
            }
            return View();
        }

        #region Route

       [HttpGet]
        public ActionResult CreateRoute()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            List<SelectListItem> itemsdrivers = new List<SelectListItem>();
            List<SelectListItem> itemscars = new List<SelectListItem>();
            var idTC = GetIdCompany().ToString();
            var routes = db.Routes.Where(x => x.IdTransportCompanies == idTC).ToList();
            var drivers = db.Drivers.Where(x => x.IdTransportCompanies == idTC).ToList();
            var cars = db.Cars.Where(x => x.IdTransportCompanies == idTC).ToList();

            foreach (var route in routes)
            {
                items.Add(new SelectListItem { Text = route.StartingPoint + "-" + route.EndPoint, Value = route.IdRoute.ToString() });
            }
            if (items != null)
            {
                ViewData["Course"] = items;
            }
            else
            {
                items.Add(new SelectListItem { Text = "Нет доступных направлений", Value = "-1" });
                ViewData["Course"] = items;
            }

            foreach (var driver in drivers)
            {
                itemsdrivers.Add(new SelectListItem { Text = driver.FirstName + " " + driver.LastName, Value = driver.IdDriver.ToString() });
            }
            if (itemsdrivers != null)
            {
                ViewData["Driver"] = itemsdrivers;
            }
            else
            {
                itemsdrivers.Add(new SelectListItem { Text = "Нет доступных водителей", Value = "-1" });
                ViewData["Driver"] = itemsdrivers;
            }
            foreach (var car in cars)
            {
                itemscars.Add(new SelectListItem { Text = car.ModelCars + " " + car.NumberPlate, Value = car.IdCar.ToString() });
            }
            if (itemscars != null)
            {
                ViewData["Car"] = itemscars;
            }
            else
            {
                itemscars.Add(new SelectListItem { Text = "Нет доступных маршруток", Value = "-1" });
                ViewData["Car"] = itemscars;
            }

            return View();
        }

        [HttpPost]
        public ActionResult CreateRoute(Models.DataRoute dataRoutes, Models.Times timees, string course, string driver, string car)
        {
            if (ModelState.IsValid == true)
            {
                var time = new Times
                {
                    ArrivalTime = dataRoutes.Times.ArrivalTime,
                    DepartureTime = dataRoutes.Times.DepartureTime
                };
                this.db.Time.Add(time);
                db.SaveChanges();

                var dataRoute = new DataRoute
                {
                    IdCar = Convert.ToInt32(car),
                    IdDriver = Convert.ToInt32(driver),
                    IdRoute = Convert.ToInt32(course),
                    IdTransportCompanies = GetIdCompany(),
                    IdTime = time.IdTime,
                    Price = dataRoutes.Price,
                    Date = dataRoutes.Date.Date,
                    Information = dataRoutes.Information
                };
                this.db.DataRoute.Add(dataRoute);
                db.SaveChanges();

                idDataroute = dataRoute.IdDataRoute;
            }
            Session["IdRoute"] = Convert.ToInt32(course);
            return RedirectToAction("DetailsWayPoints");
        }

        public ActionResult CreateWayPoints(int id)
        {
            ViewBag.idRoute = id;
            Session["Id"] = id;
            return PartialView();
        }

        [HttpPost]
        public ActionResult WayPoints(WayPoints waypoints)
        {
            int id = Convert.ToInt32(Session["Id"]);
            var wpt = new WayPointsTime
            {
                DepartureTime = waypoints.WayPointsTime.DepartureTime,
                ArrivalTime = waypoints.WayPointsTime.ArrivalTime
            };
            this.db.WayPointsTime.Add(wpt);
            db.SaveChanges();

            var time = db.WayPointsTime.FirstOrDefault(x => x.ArrivalTime == waypoints.WayPointsTime.ArrivalTime & x.DepartureTime == waypoints.WayPointsTime.DepartureTime);

            var wp = new WayPoints
            {
                NameWayPoint = waypoints.NameWayPoint,
                IdRoute = id,
                IdWayPointsTime = time.IdWayPointsTime
            };
            this.db.WayPoints.Add(wp);
            db.SaveChanges();


            var wayPoints = db.WayPoints.Where(x => x.IdRoute == id).ToList();
            return PartialView(wayPoints);
        }

        public ActionResult WayPoints(int id)
        {
            var wayPoints = db.WayPoints.Where(x => x.IdRoute == id).ToList();
            return PartialView(wayPoints);
        }

        public ActionResult DetailsWayPoints()
        {
            int idRoute = Convert.ToInt32(Session["IdRoute"]);

MarshrutkaBy/Controllers/DriverController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MarshrutkaBy.Models;

namespace MarshrutkaBy.Controllers
{
    public class DriverController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

       
        [Authorize]
        public ActionResult Index()
        {
            var IdUser = User.Identity.GetUserId();
            Drivers driver = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);
            return View(driver);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit()
        {
            var IdUser = User.Identity.GetUserId();
            Drivers driver = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);
            return View(driver);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Drivers driver)
        {
            var IdUser = User.Identity.GetUserId();
            var edit = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);

            edit.LastName = driver.LastName;
            edit.FirstName = driver.FirstName;
            edit.Birthday = driver.Birthday;
            edit.Email = driver.Email;
            edit.License = driver.License;
            edit.NumberPhone = driver.NumberPhone;

            db.SaveChanges();

            return RedirectToAction("Index");
        }

      
        public ActionResult UpcomingTrips()
        {
            var date = DateTime.Now.Date;
            var time = DateTime.Now.TimeOfDay;
            var IdUser = User.Identity.GetUserId();
            var IdDriver = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);

            var dataRoute1 = db.DataRoute.Where(x => x.IdDriver == IdDriver.IdDriver & x.Date > date);
            var dataRoute2 = db.DataRoute.Where(x => x.IdDriver == IdDriver.IdDriver & x.Date == date && x.Times.ArrivalTime >= time);
            var dataRoute = dataRoute1.Concat(dataRoute2);

            if (dataRoute.Count() != 0)
            {
                return PartialView(dataRoute.ToList());
            }
            return PartialView();
        }

       
        public ActionResult CommitedTrips()
        {
            var date = DateTime.Now.Date;
            var time = DateTime.Now.TimeOfDay;
            var IdUser = User.Identity.GetUserId();
            var IdDriver = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);

            var dataRoute1 = db.DataRoute.Where(x => x.IdDriver == IdDriver.IdDriver & x.Date < date);
            var dataRoute2 = db.DataRoute.Where(x => x.IdDriver == IdDriver.IdDriver & x.Date == date && x.Times.ArrivalTime <= time);
            var dataRoute = dataRoute1.Concat(dataRoute2);

            if (dataRoute.Count() != 0)
            {
                return PartialView(dataRoute.ToList());
            }
            return PartialView();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var order = db.Order.Where(x => x.IdDataRoute == id && x.Verification == "Подтверждено").ToList();

            if (order.Count() != 0)
            {
                return View(order);
            }
            return View();
        }

        [HttpPost]
        public ActionResult EditStatus(int id)
        {
            var order = db.Order.Find(id);
            if(order.Status == true)
            {
                order.Status = false;
            }
            else
            {
                order.Status = true;
            }

            db.SaveChanges();

            return RedirectToAction("Details", id);
        }

       
    }
}

MarshrutkaBy/Views/Admin/Cars.cshtml
@model IEnumerable<MarshrutkaBy.Models.Cars>


<h2>Автопарк</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberPlate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Services)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfSeats)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberPlate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Services)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfSeats)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Photo)
        </td>
    </tr>
}

</table>

MarshrutkaBy/Views/Admin/Create.cshtml
@model MarshrutkaBy.Models.TransportCompanies

@{
    ViewBag.Title = "Добавить";
}

<h2>Добаить компанию</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="row" style="padding-bottom: 15px;">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-6">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NumberPhone, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.NumberPhone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NumberPhone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Raiting, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Raiting, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Raiting, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control col-md-9" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-8">
                            @Html.ActionLink("Назад", "Company", new { }, new { @class = "btn btn-login col-md-4" })
                            <input type="submit" value="Добавить" class="btn btn-login  col-md-4" />

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MarshrutkaBy/Views/Admin/CreateAdminCompany.cshtml
@model MarshrutkaBy.Models.RegisterViewModel
@{
    ViewBag.Title = "CreateAdminCompany";
}

<h2>Добавить администратора компании</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="row" style="padding-bottom: 15px;">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-6">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-8">
                            @Html.ActionLink("Назад", "Company", new { }, new { @class = "btn btn-login col-md-4" })
                            <input type="submit" value="Добавить" class="btn btn-login  col-md-4" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MarshrutkaBy/Views/Admin/Delete.cshtml
@model MarshrutkaBy.Models.TransportCompanies

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4>Вы уверенны что хотите удалить компанию и все сведения о ней?</h4>
    </div>
    <div class="modal-body">
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NumberPhone)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NumberPhone)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Raiting)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Raiting)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <div class="col-md-4 null-padding-left">
                        @Html.ActionLink("Назад", "Company", new { }, new { @class = "btn btn-login-invert null-padding-left" })
                    </div>
                    <div class="col-md-offset-10">
                        @Html.ActionLink("Удалить", "DeleteTC", new { id = ViewBag.IdTc }, new { @class = "btn btn-login" })
                    </div>
                    
                </div>
            }
        </div>
    </div>
</div>

MarshrutkaBy/Views/Admin/Details.cshtml
@model MarshrutkaBy.Models.TransportCompanies

@{
    ViewBag.Title = "Подробнее";
}

<h2>Подробнее</h2>

@using (Html.BeginForm("Details", "Admin", FormMethod.Get))
{
    <div class="row" style="padding-bottom: 15px;">

        <div class="col-md-9">
            <h2>@Html.DisplayFor(model => model.Name)</h2>
        </div>
        <div class="col-md-9 text-justify">
            @Html.DisplayFor(model => model.Description)
        </div>

    </div>
    <div class="row" style="padding-bottom: 15px;">

        <div class="col-md-2">
            <b>@Html.DisplayNameFor(model => model.Email)</b>
        </div>
        <div class="col-md-2">
            @Html.DisplayFor(model => model.Email)
        </div>
        <br />
        <div class="col-md-2">
            <b>@Html.DisplayNameFor(model => model.NumberPhone)</b>
        </div>
        <div class="col-md-2">
            @Html.DisplayFor(model => model.NumberPhone)
        </div>
        <br />
        <div class="col-md-2">
            <b>@Html.DisplayNameFor(model => model.Raiting)</b>
        </div>
        <div class="col-md-2">
            @Html.DisplayFor(model => model.Raiting)
        </div>

    </div>

}
<div class="container-index">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#car" data-toggle="tab">Автопарк</a></li>
        <li><a href="#driver" data-toggle="tab">Водители</a></li>
        <li><a href="#routes" data-toggle="tab">Маршруты</a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade in active table-bordered" id="car">
            @Html.Action("Cars", "Admin", new { id = ViewBag.IdTC })
        </div>
        <div class="tab-pane fade" id="driver">
            @Html.Action("Drivers", "Admin", new { id = ViewBag.IdTC })

        </div>
        <div class="tab-pane fade" id="routes">
            @Html.Action("Routes", "Admin", new { id = ViewBag.IdTC })
        </div>
    </div>
    <div>
        @Html.ActionLink("Назад", "Company", new { }, new { @class = "btn btn-login" })
    </div>
</div>

MarshrutkaBy/Views/Admin/Edit.cshtml
@model MarshrutkaBy.Models.TransportCompanies

@{
    ViewBag.Title = "Изменить";
}

<h2>Изменить</h2>


@using (Html.BeginForm("Edit", "Admin"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdTransportCompanies)
        <div class="row" style="padding-bottom: 15px;">
            <div class="col-md-7">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NumberPhone, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.NumberPhone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NumberPhone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-9">
                            <input type="submit" value="Сохранить" class="btn btn-login" />
                            @Html.ActionLink("Назад", "Company", "Admin", new { area = "" }, new { @class = "btn btn-login-invert" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}