MarshrutkaBy/Models/Drivers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MarshrutkaBy.Models
{
    [Table("Drivers")]
    public partial class Drivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drivers()
        {
            this.DataRoute = new HashSet<DataRoute>();
        }

        [Key]
        public int IdDriver { get; set; }

        [Display(Name = "Фамилия")]
        [Required]
        public string LastName { get; set; }

        [Display(Name = "Имя")]
        [Required]
        public string FirstName { get; set; }

        
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "День рождения")]
        public DateTime Birthday { get; set; }

        [Display(Name = "Лицензия")]
        [Required]
        public string License { get; set; }

        [Display(Name = "Номер телефона")]
        [Required]
        public string NumberPhone { get; set; }

        [Required]
        public string Email { get; set; }

        [Display(Name = "Рейтинг")]
        public int Raiting { get; set; }

        [Display(Name = "Фото")]
        public string Photo { get; set; }

        [Required]
        public string UserId { get; set; }

        [Required]
        public string IdTransportCompanies { get; set; }

        public virtual TransportCompanies TransportCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataRoute> DataRoute { get; set; }
    }
}

MarshrutkaBy/Controllers/DriverController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MarshrutkaBy.Models;

namespace MarshrutkaBy.Controllers
{
    public class DriverController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

       
        [Authorize]
        public ActionResult Index()
        {
            var IdUser = User.Identity.GetUserId();
            Drivers driver = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);
            return View(driver);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit()
        {
            var IdUser = User.Identity.GetUserId();
            Drivers driver = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);
            return View(driver);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Drivers driver)
        {
            var IdUser = User.Identity.GetUserId();
            var edit = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);

            edit.LastName = driver.LastName;
            edit.FirstName = driver.FirstName;
            edit.Birthday = driver.Birthday;
            edit.Email = driver.Email;
            edit.License = driver.License;
            edit.NumberPhone = driver.NumberPhone;

            db.SaveChanges();

            return RedirectToAction("Index");
        }

      
        public ActionResult UpcomingTrips()
        {
            var date = DateTime.Now.Date;
            var time = DateTime.Now.TimeOfDay;
            var IdUser = User.Identity.GetUserId();
            var IdDriver = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);

            var dataRoute1 = db.DataRoute.Where(x => x.IdDriver == IdDriver.IdDriver & x.Date > date);
            var dataRoute2 = db.DataRoute.Where(x => x.IdDriver == IdDriver.IdDriver & x.Date == date && x.Times.ArrivalTime >= time);
            var dataRoute = dataRoute1.Concat(dataRoute2);

            if (dataRoute.Count() != 0)
            {
                return PartialView(dataRoute.ToList());
            }
            return PartialView();
        }

       
        public ActionResult CommitedTrips()
        {
            var date = DateTime.Now.Date;
            var time = DateTime.Now.TimeOfDay;
            var IdUser = User.Identity.GetUserId();
            var IdDriver = db.Drivers.FirstOrDefault(x => x.UserId == IdUser);

            var dataRoute1 = db.DataRoute.Where(x => x.IdDriver == IdDriver.IdDriver & x.Date < date);
            var dataRoute2 = db.DataRoute.Where(x => x.IdDriver == IdDriver.IdDriver & x.Date == date && x.Times.ArrivalTime <= time);
            var dataRoute = dataRoute1.Concat(dataRoute2);

            if (dataRoute.Count() != 0)
            {
                return PartialView(dataRoute.ToList());
            }
            return PartialView();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var order = db.Order.Where(x => x.IdDataRoute == id && x.Verification == "Подтверждено").ToList();

            if (order.Count() != 0)
            {
                return View(order);
            }
            return View();
        }

        [HttpPost]
        public ActionResult EditStatus(int id)
        {
            var order = db.Order.Find(id);
            if(order.Status == true)
            {
                order.Status = false;
            }
            else
            {
                order.Status = true;
            }

            db.SaveChanges();

            return RedirectToAction("Details", id);
        }

       
    }
}

MarshrutkaBy/Views/Driver/CommitedTrips.cshtml
@model IEnumerable<MarshrutkaBy.Models.DataRoute>
<h2>Совершённые поездки</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Routes.StartingPoint)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Routes.EndPoint)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Times.DepartureTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Times.ArrivalTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Information)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cars.ModelCars)
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Routes.StartingPoint)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Routes.EndPoint)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Times.DepartureTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Times.ArrivalTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Information)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cars.ModelCars)
                </td>
                <td>
                    @Html.ActionLink("Список пассажиров", "Details", new { id = Convert.ToString(item.IdDataRoute) }, new { @class = "btn btn-order" })
                </td>
            </tr>
        }

    }
</table>

MarshrutkaBy/Views/Driver/Details.cshtml
@model IEnumerable<MarshrutkaBy.Models.Orders>

@{
    ViewBag.Title = "Список пассажиров";

    AjaxOptions ajaxOptions = new AjaxOptions
    {
        UpdateTargetId = "result",
        Url = Url.Action("EditStatus", "Driver")
    };

}

<h2>Список пассажиров</h2>
@if (Model != null)
{

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdOrder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Registration.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Registration.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Registration.MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Registration.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
        </tr>

    @foreach (var item in Model)
    {
        
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdOrder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Registration.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Registration.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Registration.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Registration.PhoneNumber)
            </td>
        
            <td>
                @Html.CheckBoxFor(modelItem => item.Status, new { id = item.IdOrder, @class = "toggle checkbox", data_url = Url.Action("EditStatus", "Driver") })
            </td>
        </tr>
    }

    </table>
}
else
{
    <h4>Список пуст</h4>
}

<div class="form-group">
    <div class="">
        @Html.ActionLink("Назад", "Index", "Driver", new { area = "" }, new { @class = "btn btn-login" })
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            $('.toggle').change(function () {
                var self = $(this);
                var url = self.data('url');
                var id = self.attr('id');
               

                $.ajax({
                    url: url,
                    data: { id: id },
                    type: 'POST',
                    success: function (response) {
                        alert(response);
                    }
                });
            });
        });
    </script>
}

@Scripts.Render("~/Scripts/jquery-3.1.1.min.js")
@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")

MarshrutkaBy/Views/Driver/Edit.cshtml
@model MarshrutkaBy.Models.Drivers

@{
    ViewBag.Title = "Редактирование";
}

<h2>Редактирование</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdDriver)
        <div class="row" style="padding-bottom: 15px;">
            <div class="col-md-6">
                <hr />
                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <div class='input-group date'>
                            @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control datepicker datetimepicker" } })
                            @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.License, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.License, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.License, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NumberPhone, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.NumberPhone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NumberPhone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        @Html.ActionLink("Назад", "Index", "Driver", new { area = "" }, new { @class = "btn btn-login-invert" })
                        <input type="submit" value="Сохранить" class="btn btn-login" />
                    </div>
                </div>
            </div>
        </div>
    </div>

}

@section Scripts {
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    @Scripts.Render("~/Scripts/moment-with-locales.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker.min.js")

    <script type="text/javascript">
        $(function () { // will trigger when the document is ready
            $('.datepicker').datepicker(); //Initialise any date pickers
            $.datepicker.regional['ru'] = {
                prevText: 'Пред',
                nextText: 'След',
                monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
                'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
                monthNamesShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
                dayNames: ['воскресенье', 'понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота'],
                dayNamesShort: ['вск', 'пнд', 'втр', 'срд', 'чтв', 'птн', 'сбт'],
                dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                weekHeader: 'Не',
                dateFormat: 'dd/mm/yy',
                firstDay: 1,
                minDate: 0,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ''
            };
            $.datepicker.setDefaults($.datepicker.regional['ru']);
        });

    </script>
}

MarshrutkaBy/Views/Driver/Index.cshtml
@model MarshrutkaBy.Models.Drivers

@{
    ViewBag.Title = "Главная";
}


    <div class="driver-info row">
        <div class="col-md-2">
            <img class="driver-photo" src="~/Images/default_avatar.jpg" />
        </div>
            <div class="col-md-4">
                <h2 class="h2-margin-null">
                    @Html.DisplayFor(model => model.LastName)
                    @Html.DisplayFor(model => model.FirstName)
                </h2>
                <h4>
                    @Html.DisplayNameFor(model => model.License):
                    @Html.DisplayFor(model => model.License)
                </h4>
                <h4>
                    @Html.DisplayNameFor(model => model.NumberPhone):
                    @Html.DisplayFor(model => model.NumberPhone)
                </h4>
                <h4>
                    @Html.DisplayNameFor(model => model.Email):
                    @Html.DisplayFor(model => model.Email)
                </h4>
                <h4>
                    @Html.DisplayNameFor(model => model.Raiting):
                    @Html.DisplayFor(model => model.Raiting)
                </h4>
                <p>
                    @Html.ActionLink("Изменить", "Edit", new { id = Model.IdDriver }, new { @class = "btn btn-order" })
                </p>
            </div>

        </div>


    <div class="container-index">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#upcoming" data-toggle="tab">Предстоящие поездки</a></li>
            <li><a href="#commited" data-toggle="tab">Совершённые поездки</a></li>
        </ul>

        <div class="tab-content table-bordered">
            <div class="tab-pane fade in active" id="upcoming">
                @Html.Action("UpcomingTrips", "Driver")
            </div>
            <div class="tab-pane fade" id="commited">
                @Html.Action("CommitedTrips", "Driver")
            </div>
        </div>
    </div>

MarshrutkaBy/Views/Driver/UpcomingTrips.cshtml
@model IEnumerable<MarshrutkaBy.Models.DataRoute>

<h2>Предстоящие поездки</h2>

@if (Model != null)
{

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Routes.StartingPoint)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Routes.EndPoint)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Times.DepartureTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Times.ArrivalTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Information)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cars.ModelCars)
            </th>
            <th></th>
        </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Routes.StartingPoint)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Routes.EndPoint)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Times.DepartureTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Times.ArrivalTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Information)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cars.ModelCars)
                    </td>
                    <td>
                        @Html.ActionLink("Список пассажиров", "Details", new { id = item.IdDataRoute }, new { @class = "btn btn-order" }) 
                    </td>
                </tr>
            }

    </table>

}
else {
    <h4>Список пуст</h4>
}